@baseUrl = http://localhost:8000
@accessToken = Bearer {{login.response.body.bearer.access}}
@refreshToken = {{login.response.body.bearer.refresh}}
###

# @name login
post {{baseUrl}}/auth/login
Content-Type: application/json

 {
    "userName":"alican2",
    "email":"alican2@example.com",
    "password":"Aa*41234"
 }

### 

# @name register
post {{baseUrl}}/auth/register
Content-Type: application/json

 {
    "userName":"tosunpasa1",
    "email":"tosunpasa1@gmail.com",
    "password":"Aa*41234"
 }

### 

# @name logout
post {{baseUrl}}/auth/logout
Content-Type: application/json

 {
    "ref":"test3",
    "email":"test3@example.com",
    "password":"12341234"
 }

### 
# @name refresh
post {{baseUrl}}/auth/refresh
Content-Type: application/json

 {
    "refresh":"{{refreshToken}}"
  
 }

### 

# @name users
get {{baseUrl}}/users
Content-Type: application/json

 {
    "userName":"admin",
    "email":"admin@example.com",
    "password":"12341234"
 }

### 

# @name users/:id
delete {{baseUrl}}/users/
Content-Type: application/json

  {
    "userName":"parola",
    "password":"54545454"
  }


### 

# @name tokens
get {{baseUrl}}/tokens
Content-Type: application/json


 {
    "userId":"68c976381dda70627b867b9c",
    "token":"asdasasa21231342432scas234234dasdas"
 }

###

# @name tokens/:id
put {{baseUrl}}/tokens/
Content-Type: application/json

 {

 }

###

###

# @name stars/
get {{baseUrl}}/stars/
Content-Type: application/json

 {
    "creatorUserId":"68c974bc55a8100774887d3d" ,
    "value": 5
 }

###

# @name stars/:id
delete {{baseUrl}}/stars/68c97b935890dad8ba598ac6
Content-Type: application/json

 {

 }

###

# @name comments/
get {{baseUrl}}/comments
Content-Type: application/json

 {
    "creatorUserId":"68c974bc55a8100774887d3d",
    "content":"asvasvavs"

 }

###

# @name comments/:id
delete {{baseUrl}}/comments/68c97ed96341273303f70829
Content-Type: application/json

 {
    "creatorUserId":"68c974bc55a8100774887d3d",
    "content":"agaaa"
 }

###

# @name mealCategories/
get {{baseUrl}}/mealCategories
Content-Type: application/json

 {
    "categoryName":"tatlilar"

 }

###

# @name mealCategories/:id
put {{baseUrl}}/mealCategories/68c986431ddbb6a59d564282
Content-Type: application/json

 {
    "categoryName":""
 }

###

# @name recipes/
post {{baseUrl}}/recipes
Content-Type: application/json

 {
    "recipeName":"patlicanli kabak",
    "userId":"68c966ba4080886471376b2a",
    "description":"patlicanli kabak",
    "ingredients":["patlican","kabak"],
    "steps":["patlican pisir", "kabak pisir"],
    "imageUrl":"https://i.lezzet.com.tr/images-xxlarge-recipe/fransiz-mutfaginin-yildizi-ratatouille-9ce044bd-4bea-4c0b-a8ef-da47b55070e6.jpg",
    "mealCategories":["68c986431ddbb6a59d564282"],
    "stars":["68c986431ddbb6a59d564282"]


 }

###

# @name recipes/:id
put {{baseUrl}}/recipes/
Content-Type: application/json

 {
    "categoryName":""
 }

###


